--Advanced challenge 1 START
SELECT TITLE, RETAIL - COST AS "Profit"
FROM BOOKS
WHERE (RETAIL - COST) >= 10
ORDER BY RETAIL - COST DESC
;
--Advanced challenge 1 END

--Advanced challenge 2 START
SELECT TITLE, CATEGORY, COST, PUBID
FROM BOOKS
WHERE COST >= 45 AND (PUBID = 1 OR PUBID = 3) AND (CATEGORY = 'COMPUTER' OR CATEGORY = 'FAMILY LIFE')
;
--Advanced challenge 2 END