-- LINE COMMENTS
SELECT LNAME||', '||FNAME "Author", LASTNAME, FIRSTNAME, ADDRESS, CITY, STATE, ZIP, REGION, EMAIL
FROM AUTHOR, LITERARYAGENTS 
ORDER BY EMAIL
;
--
SELECT LNAME||', '||FNAME "Author", TITLE, LASTNAME, FIRSTNAME, ADDRESS, CITY, STATE, ZIP, REGION, EMAIL
FROM AUTHOR A, LITERARYAGENTS LA, BOOKS B, BOOKAUTHOR BA
WHERE A.AUTHORID = BA.AUTHORID AND BA.ISBN = B.ISBN
ORDER BY EMAIL
;