SQL> show spool
spool ON
SQL> show user
USER is "SYSTEM"
SQL> create user C##J21_BeharryMathias IDENTIFIED by password;

User created.

SQL> grant dba to C##J21_BeharryMathias;

Grant succeeded.

SQL> disc
Disconnected from Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0
SQL> conn
Enter user-name: C##J21_BeharryMathias
Connected.
SQL> 
SQL> 
SQL> 
SQL> 
SQL> SHOW USER
USER is "C##J21_BEHARRYMATHIAS"
SQL> SHOW SPOOL
spool ON
SQL> SPOOL OFF
